---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: busybox-placement
spec:
  clusterSets:
  - drset
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            name: beijing

